config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get '/login', to: 'sessions#new'

  post '/login' , to: 'sessions#create' 

  delete '/logout' , to: 'sessions#destroy'

  post '/respond' , to: 'invitations#respond'

  post '/request_respond' , to: 'requests#request_respond'  


  resources :comments
  resources :posts
  resources :requests
  resources :invitations
  
  resources :groups
  resources :users
  #root 'users#index'
  #root 'static_pages#home'
  root 'static_pages#practice'
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :memberships , dependent: :destroy
	has_many :users , :through => :memberships
	has_many :invitations , dependent: :destroy
	has_many :requests , dependent: :destroy

	validates :name , presence: true , uniqueness: {case_sensitive: false} , length: { maximum: 6 }	
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user , only: [:show,:edit,:update,:destroy,:index,:new,:create]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :correct_user , only: [:show, :edit, :update, :destroy] 
  
  def index
    @groups = Group.joins(:memberships).where("memberships.user_id=#{current_user.id}")
  end

  def show
    session[:group_id] = params[:id]
    @posts = Membership.joins(:group).where(group_id: session[:group_id]).joins("INNER JOIN posts ON memberships.id = posts.membership_id").select("posts.id,posts.content , posts.created_at,memberships.user_id").order("posts.created_at DESC")
    @post = Post.new
    @comment = Comment.new
  end

  
  def new
    @group = Group.new

  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    #@user = current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
    @member = Membership.new(user_id: current_user.id , group_id: @group.id,is_admin: true)
    @member.save
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
       params.require(:group).permit(:name)
    end

    def correct_user
      member = Membership.find_by(user_id: current_user.id , group_id: params[:id])
      if member.nil?
        flash[:danger] = "You are not member of this group,please join"
        redirect_to new_request_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= form_for(@group, url: groups_path ) do |f| %>
		  <%= render 'shared/error_messages_groups' %>
		  <div class="field">
		    <%= f.label :name %>
		    <%= f.text_field :name , class: 'form-control'%>
		  </div>

		  <div class="actions">
		    <%= f.submit "Create Group" , class: 'btn btn-primary' %>
		  </div>
		<% end %>
	</div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>
<% @groups.each do |group| %>
      <ul>
        <li><%= link_to group['name'] , group %></li>
        <td><%#= link_to 'Show', group_path(group) %></td>
        <td><%#= link_to 'Edit', edit_group_path(group) %></td>
        <td><%#= link_to 'Destroy', group_path(group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </ul>
    <% end %> 
<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= render 'posts/form', post: @post %>
  	<%= render 'shared/post_card' , post: @post %>  
  </div>
</div>  

<div class = "add-people">
  <%= link_to 'Add people' , new_invitation_path %>
</div>
      