config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get '/login', to: 'sessions#new'

  post '/login' , to: 'sessions#create' 

  delete '/logout' , to: 'sessions#destroy'

  post '/respond' , to: 'invitations#respond'

  post '/request_respond' , to: 'requests#request_respond'  


  resources :comments
  resources :posts
  resources :requests
  resources :invitations
  
  resources :groups
  resources :users
  #root 'users#index'
  #root 'static_pages#home'
  root 'static_pages#practice'
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :group
	belongs_to :user , :foreign_key => 'sender_id' 
	validates_uniqueness_of :sender_id, :scope => [:group_id]
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :logged_in_user , only: [:show,:edit,:update,:destroy,:request_respond,:index,:request_respond]
  def index
    @requests = Request.joins("INNER JOIN memberships ON requests.group_id = memberships.group_id").select(:id,:group_id,:sender_id).where("memberships.is_admin=true AND memberships.user_id = #{current_user.id} AND requests.is_granted IS NULL")
  end

  
  def show
  end

  def new
    @requests = Group.select(:id,:name).where.not(id:Group.select(:id).where(id:Membership.select(:group_id).where(user_id:current_user.id)))
  end

  def edit
  end

  
  def create
    @request = Request.new(sender_id: current_user.id , group_id: params[:request][:group_id])
    @request.save
    redirect_to new_request_path
  end

  def update
  end

  def destroy
  end

  def request_respond
    message = params[:commit]
    request = Request.find_by(id: params[:request_respond][:request_id])
    if message == "Yes"
      request.update_attributes(is_granted: true)
      membership = Membership.new(user_id: params[:request_respond][:sender_id] , group_id: params[:request_respond][:group_id] , is_admin: false)
      membership.save
    else
      request.update_attributes(is_granted: false)
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<% @requests.each do |request| %>
  <ul>
     <li>
      <div class="actions">
        <%= form_for(:request,url: requests_path) do |f| %>
          
          <%= request['name'] %>
          <%= f.hidden_field :group_id, :value => request['id'].to_i%>
          <span>
          <div class = "sub-btn">
            <%= f.submit "Join", class: "btn btn-primary" %>
          </div>
          </span>
        <% end %>
      </div>
    </li>
  </ul>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<h1>Requests</h1>
    <% @requests.each do |request| %>
    <ul>
     <li>
     <% group =  Group.select(:id,:name).where(id: request['group_id'].to_i).first %>
     <% user =  User.select(:id,:name).where(id: request['sender_id'].to_i).first %>
      <div class="actions">
        <%= form_for(:request_respond,url: request_respond_path) do |f| %>
          Request for group <%= group['name'] %>
          from user <%= user['name'] %>
          <%= f.hidden_field :request_id, :value => request['id'].to_i%>
          <%= f.hidden_field :group_id, :value => group['id'].to_i%>
          <%= f.hidden_field :sender_id, :value => user['id'].to_i%>
          <div class = "sub-btn">
            <%= f.submit "Yes", class: "btn btn-primary" %>
          </div>
          <div class = "sub-btn">
            <%= f.submit "No", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </li>
  </ul>
    <% end %>
  </div>
  </div>

app/views/requests/new.html.erb
<h1>All Groups</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= render 'form', request: @request %>

	<%#= link_to 'Back', requests_path %>
  </div>
 </div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>